<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <ItemGroup>
    <ProjectReference Include="..\TemporalDemo.ApiService\TemporalDemo.ApiService.csproj" />
    <ProjectReference Include="..\TemporalDemo.Worker\TemporalDemo.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.5.4" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>0eab1a45-a4d9-4644-a90d-5edcce019b85</UserSecretsId>
    <AspireUseCliBundle>true</AspireUseCliBundle>
  </PropertyGroup>

</Project>
